
/// A structure representing a matrix shape, which holds the shape and strides of a matrix.
/// A 3x3 matrix will have a shape of [3, 3] with strides of [3, 1]
/// Reference for implementation: https://substack.com/@getcode/p-118556536
/// 
/// # Fields
/// 
/// * `shape` - A vector that has as many elements as there are dimensions in the matrix, and stores the 
///             length of each dimension. 
/// * `strides` - A vector that also has as many elements as there are dimensions and stores the offset in the 
///               buffer between successive elements in that dimension.
#[derive(Clone)]
pub struct MatrixShape{
    shape: Vec<usize>, 
    strides: Vec<usize>,
}

impl MatrixShape {
    pub fn new(shape: Vec<usize>) -> MatrixShape {
        if shape.is_empty() { panic!("Shape cannot be empty for strider"); }

        // We're interpreting the buffer in row-major order, which means that 
        // consecutive elements in the tensor's rows are consecutive in the buffer.
        // As a result, we know that the last (rightmost) stride sₙ₋₁ = 1.
        let mut strides = vec![1; shape.len()];
        for i in (0..shape.len() - 1).rev() {
            strides[i] = strides[i + 1] * shape[i + 1];
        }

        MatrixShape {
            shape: shape,
            strides: strides,
        }   
    }

    pub fn dimensions(&self) -> Vec<usize>{
        self.shape.clone()
    }
    /// Computes a single index in a one dimensional buffer from an n-dimensional index
    /// This is done by taking the dot product of the index and strides arrays.
    /// 
    /// e.g. If index = [2, 3] and strides = [4, 5], the calculation would be:
    ///     2 ⋅ 4 + 3 ⋅ 5 
    ///   = 8 + 15 
    ///   = 23
    pub fn index_buffer(&self, n_dimensional_index: &[usize]) -> usize {
        //this validation would be slower for huge matrices, but shouldn't be too bad for most cases
        if n_dimensional_index.len() != self.shape.len() { panic!("Index length must equal shape length") }
        for i in 0..n_dimensional_index.len(){
            if n_dimensional_index[i] > self.shape[i] {panic!("Index {} out of bounds", i)}
        }
        let single_index = n_dimensional_index.iter() //create an iterator over the 1d matrix
            .zip(self.strides.iter()) //pair index iterator with strides
            .map(|(&index, &stride)| index * stride) // Get product of index * stride
            .sum::<usize>(); // sum the products generated by the map operation
        return single_index;
    }

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strider_new_valid_shape() {
        let shape = vec![3, 3];
        let strider = MatrixShape::new(shape.clone());
        assert_eq!(strider.shape, shape);
        assert_eq!(strider.strides, vec![3, 1]);
    }

    #[test]
    #[should_panic(expected = "Shape cannot be empty for strider")]
    fn test_strider_new_empty_shape() {
        MatrixShape::new(vec![]);
    }

    #[test]
    fn test_strider_new_single_dimension() {
        let shape = vec![5];
        let strider = MatrixShape::new(shape.clone());
        assert_eq!(strider.shape, shape);
        assert_eq!(strider.strides, vec![1]);
    }

    #[test]
    fn test_strider_new_multi_dimension() {
        let shape = vec![2, 3, 4];
        let strider = MatrixShape::new(shape.clone());
        assert_eq!(strider.shape, shape);
        assert_eq!(strider.strides, vec![12, 4, 1]);
    }

    #[test]
    fn test_index_buffer_single_dimension() {
        let shape = vec![5];
        let strider = MatrixShape::new(shape);
        assert_eq!(strider.index_buffer(&[0]), 0);
        assert_eq!(strider.index_buffer(&[1]), 1);
        assert_eq!(strider.index_buffer(&[4]), 4);
    }

    #[test]
    fn test_index_buffer_two_dimensions() {
        let shape = vec![3, 3];
        let strider = MatrixShape::new(shape);
        assert_eq!(strider.index_buffer(&[0, 0]), 0);
        assert_eq!(strider.index_buffer(&[0, 1]), 1);
        assert_eq!(strider.index_buffer(&[1, 0]), 3);
        assert_eq!(strider.index_buffer(&[2, 2]), 8);
    }

    #[test]
    fn test_index_buffer_three_dimensions() {
        let shape = vec![2, 3, 4];
        let strider = MatrixShape::new(shape);
        assert_eq!(strider.index_buffer(&[0, 0, 0]), 0);
        assert_eq!(strider.index_buffer(&[0, 1, 2]), 6);
        assert_eq!(strider.index_buffer(&[1, 0, 0]), 12);
        assert_eq!(strider.index_buffer(&[1, 2, 3]), 23);
    }

    #[test]
    #[should_panic(expected = "Index length must equal shape length")]
    fn test_index_buffer_invalid_index_length() {
        let shape = vec![3, 3];
        let strider = MatrixShape::new(shape);
        strider.index_buffer(&[1, 2, 3, 4]); // This should panic because the index length is greater than the shape length
    }

    #[test]
    #[should_panic]
    fn test_index_buffer_out_of_bounds_index() {
        let shape = vec![3, 3];
        let strider = MatrixShape::new(shape);
        let result = strider.index_buffer(&[4, 4]); // This should panic because the index is out of bounds
    }
}
